config/routes.rb
Rails.application.routes.draw do
  resources :contacts

  root 'contacts#index'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/contact.rb
class Contact < ApplicationRecord
	#association:
	belongs_to :group
	#validation:
	validates :name, :surname, :phone, :address, :phone, presence: true
	validates :email, format: { with: /\A([^@\s]+)@((?:[-a-z0-9]+\.)+[a-z]{2,})\z/i}
	validates :phone, numericality: true, length: 9..13
end

app/models/group.rb
class Group < ApplicationRecord
	#association:
	has_many :contacts
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/contacts_controller.rb
class ContactsController < ApplicationController
  before_action :set_contact, only: [:show, :edit, :update, :destroy]

  def index
  	if params[:group_id]
      @group = Group.find(params[:group_id])
      @contacts = @group.contacts.order('surname')
    else
      @contacts = Contact.order('surname')
    end
  end

  def new
  	@contact = Contact.new
  end

  def edit
  end

  def create
  	@contact = Contact.new(contact_params)
  		if @contact.save
  			redirect_to @contact, notice: 'Contact was successfully created.'
  		else
  			render :new
  		end
  end

  def update
  	if @contact.update(contact_params)
  		redirect_to @contact, notice: 'Contact was successfully updated'
  	else
  		render :edit 
  	end
	end

  def show
  end

  def destroy
  	@contact.destroy
  		redirect_to contacts_path, notice: 'Contact was successfully destroyed'
  end

  private 

	def set_contact
		@contact = Contact.find(params[:id])
	end

	def contact_params
		params.require(:contact).permit(:name, :surname, :phone, :address, :email, :important, :group_id)
	end


end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/contacts_helper.rb
module ContactsHelper
end

app/views/contacts/_form.html.erb
<%= simple_form_for(@contact, html: {multipart: true })  do |f| %>
  <% if @contact.errors.any? %>
		<h3><%= pluralize(@contact.errors.count, "error") %> prohibited this contact from being saved:</h3>
      <ul>
        <% @contact.errors.full_messages.each do |msg| %>
          <li><%= msg %></li>
          <% end %>
      </ul>
   	<% end %>


  <%= f.input :name, label: 'Name', placeholder: 'Andy' %>
  <%= f.input :surname, label: 'Surname', placeholder: 'Bush' %>
  <%= f.input :email, label: 'Email', placeholder: 'user@domain.com' %>
  <%= f.input :phone, label: 'Phone', placeholder: '123456789' %>
  <%= f.input :address, label: 'Address', placeholder: 'Cracow, Lea 12/58', as: :text %>
  <%= f.collection_select :group_id, Group.all, :id, :name, :prompt => "Select a group" %>
  <%= f.input :important, label: 'Important contact', inline_label: 'This contact is important for me?' %>
  <%= f.button :submit, class: "btn btn-primary" %>
  <%= link_to "Cancel", contacts_path, class: "btn btn-primary" %> 
<% end %>			

app/views/contacts/edit.html.erb
<div class="panel panel-default">
  <div class="panel-heading">
    <strong>Edit Contact</strong>
  </div> 
  <%= render 'form' %>
</div>

app/views/contacts/index.html.erb
<div class="panel panel-primary">
	<table class="table">

	<% @contacts.each do |contact| %>

	<tr>
		<td class="middle">
					<h3 class="media-heading"><%= contact.name %> <%= contact.surname%> 
						<% if contact.important? %>
            	<span class="star">
          			<span class="glyphicon glyphicon-star", aria-hidden="true"></span>
          		</span>	
            <% end %>       
          </h3>

          <p><i class="glyphicon glyphicon-phone"> <%= contact.phone %></i></p>					
          <p><i class="glyphicon glyphicon-globe"> <%= contact.email %></i></p>	
					<address>
						<i><%= contact.address %></i>
					</address>
		

         <td width="200" class="middle">
          <div>

          	<%= link_to contact_path(contact), class: "btn btn-circle btn-default btn-xs", title: "Show" do %>
          		<i class="glyphicon glyphicon-info-sign"></i>
          	<% end %>
            <%= link_to edit_contact_path(contact), class: "btn btn-circle btn-default btn-xs", title: "Edit" do %>
              <i class="glyphicon glyphicon-edit"></i>
            <% end %>
            <%= link_to contact_path(contact), :method => :delete, class: "btn btn-circle btn-danger btn-xs", title: "Delete", data: { confirm: "Are you sure ?" } do %>
              <i class="glyphicon glyphicon-trash"></i>
            <% end %>            
          </div>
        </td>
	</tr>
	<% end %>
	</table>
</div>

app/views/contacts/new.html.erb
<div class="panel panel-default">
  <div class="panel-heading">
    <strong>Add Contact</strong>
  </div> 
  <%= render 'form' %>
</div>

app/views/contacts/show.html.erb
<div class="panel panel-primary">
	<div class="head">
	<div class="medium">

	<h1> <%= @contact.name %> <%= @contact.surname %> </h1>
	<h3> <span class="glyphicon glyphicon-phone"> <%= @contact.phone %></span><br>
	<span class="glyphicon glyphicon-globe"> <a href="mailto:"><%= @contact.email %></a></span><br>
	<span class="glyphicon glyphicon-envelope"> <%= @contact.address %></span><br>
	<span class="glyphicon glyphicon-user"> <%= @contact.group.name %></span class="glyphicon glyphicon-user"> </h3><br>
	<%= link_to "Edit", edit_contact_path(@contact), class: 'btn btn-primary' %>
	<%= link_to "Delete", contact_path(@contact), :method => :delete, class: 'btn btn-primary', data: {confirm: 'Are you sure?'} %>
	</div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Mycontact</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
    <script src="https://code.jquery.com/ui/1.12.1/jquery-ui.js"></script>

</head>
<body>
  <!-- navbar -->
    <nav class="navbar navbar-inverse navbar-fixed-top">
      <div class="container">
        <div class="navbar-header">

          <%= link_to "My contact", root_path, class: "navbar-brand" %>          
        </div>
        <!-- /.navbar-header -->
        <div class="collapse navbar-collapse" id="navbar-collapse">
          <div class="nav navbar-right navbar-btn">
            <%= link_to new_contact_path, class: "btn btn-primary" do %>
              <i class="glyphicon glyphicon-plus"></i> 
              Add Contact
            <% end %>
          </div>
        </div>
      </div>
    </nav>
  
  <!-- content -->
    <div class="container">
      <div class="row">
        <div class="col-md-3">
          <div class="list-group">
            <!-- set active links -->
            <% active = params[:group_id] == nil ? 'active' : '' %>

            <%= link_to contacts_path, class: "list-group-item #{active}" do %>
                <b>All Contacts</b> <span class="badge"><%= Contact.count %></span>
              <% end %>
            
            <% Group.all.each do |group| %>
              <% active = params[:group_id].to_i == group.id ? 'active' : '' %>
              <%= link_to contacts_path(group_id: group.id), class: "list-group-item #{active}" do %>
                <%= group.name %> <span class="badge"><%= group.contacts.count %></span>
              <% end %>
            <% end %>

          </div>
        </div>  

        <div class="col-md-6">

          <%= yield %>
          
        </div>
      </div>
    </div>

</body>
</html>